module.exports = {
  Harbor: {
    Sunny: {
      grip: 3,
      handling: 4,
      deceleration: 3,
      torquehigh: 3,
      torquelow: 1,
      topspeed: 3,
      reliability: 1,
      weight: 1,
      curves: 4,
      straights: 4,
      rain: 0,
      fog: 0,
      rocky: 1,
    },
    Rainy: {
      grip: 5,
      handling: 4,
      deceleration: 4,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 1,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 2,
      rain: 4,
      fog: 0,
      rocky: 1,
    },
    Foggy: {
      grip: 3,
      handling: 4,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 1,
      topspeed: 2,
      reliability: 2,
      weight: 1,
      curves: 3,
      straights: 2,
      rain: 0,
      fog: 3,
      rocky: 1,
    },
    Snowy: {
      grip: 6,
      handling: 5,
      deceleration: 5,
      torquehigh: 1,
      torquelow: 1,
      topspeed: 0,
      reliability: 3,
      weight: 2,
      curves: 3,
      straights: 1,
      rain: 6,
      fog: 2,
      rocky: 1,
    },
  },
  'I-69': {
    Sunny: {
      grip: 1,
      handling: 2,
      deceleration: 1,
      torquehigh: 4,
      torquelow: 1,
      topspeed: 5,
      reliability: 2,
      weight: 1,     // lighter is a mild advantage
      curves: 1,
      straights: 5,
      rain: 0,
      fog: 0,
      rocky: 0,
    },
    Rainy: {
      grip: 4,
      handling: 3,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 2,   // still matters, but you can't safely max it
      reliability: 3,
      weight: 2,
      curves: 1,
      straights: 3,
      rain: 4,
      fog: 0,
      rocky: 0,
    },
    Foggy: {
      grip: 2,
      handling: 3,
      deceleration: 3,
      torquehigh: 3,
      torquelow: 1,
      topspeed: 3,
      reliability: 2,
      weight: 1,
      curves: 1,
      straights: 4,
      rain: 0,
      fog: 3,
      rocky: 0,
    },
    Snowy: {
      grip: 5,
      handling: 4,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 1,
      reliability: 3,
      weight: 2,
      curves: 1,
      straights: 2,
      rain: 6,
      fog: 2,
      rocky: 0,
    },
  },
  'Groom Lake': {
    Sunny: {
      grip: 4,
      handling: 3,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 3,
      topspeed: 1,
      reliability: 4,
      weight: 2,
      curves: 1,
      straights: 3,
      rain: 0,
      fog: 0,
      rocky: 5,
    },
    Rainy: {
      grip: 6,
      handling: 4,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 3,
      topspeed: 0,
      reliability: 5,
      weight: 2,
      curves: 1,
      straights: 2,
      rain: 5,
      fog: 0,
      rocky: 6,
    },
    Foggy: {
      grip: 4,
      handling: 4,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 1,
      reliability: 4,
      weight: 2,
      curves: 1,
      straights: 2,
      rain: 0,
      fog: 4,
      rocky: 5,
    },
    Snowy: {
      grip: 7,
      handling: 5,
      deceleration: 5,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 5,
      weight: 3,
      curves: 1,
      straights: 1,
      rain: 6,
      fog: 3,
      rocky: 6,
    },
  },
  Hillside: {
    Sunny: {
      grip: 3,
      handling: 4,
      deceleration: 3,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 1,
      reliability: 2,
      weight: 1,       // lighter cars handle elevation + tight corners well
      curves: 5,
      straights: 1,
      rain: 0,
      fog: 0,
      rocky: 2,        // minor potholes
    },

    Rainy: {
      grip: 5,
      handling: 5,
      deceleration: 4,
      torquehigh: 0,
      torquelow: 1,
      topspeed: 0,
      reliability: 3,
      weight: 1,
      curves: 4,
      straights: 1,
      rain: 4,
      fog: 0,
      rocky: 3,
    },

    Foggy: {
      grip: 4,
      handling: 5,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 0,
      reliability: 3,
      weight: 1,
      curves: 5,
      straights: 1,
      rain: 0,
      fog: 4,
      rocky: 2,
    },
    Snowy: {
      grip: 6,
      handling: 6,
      deceleration: 5,
      torquehigh: 0,
      torquelow: 2,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 5,
      straights: 0,
      rain: 6,
      fog: 2,
      rocky: 3,
    },
  },
  Quarry: {
    Sunny: {
      grip: 3,           // dirt needs grip
      handling: 2,
      deceleration: 2,
      torquehigh: 1,
      torquelow: 3,      // off-road torque for small hills
      topspeed: 0,
      reliability: 4,    // rocks, uneven terrain
      weight: 2,         // lighter = better here
      curves: 3,         // long gradual curves
      straights: 1,
      rain: 0,
      fog: 0,
      rocky: 5,          // very rocky environment
    },

    Rainy: {
      grip: 5,           // wet dirt = brutal for traction
      handling: 3,
      deceleration: 3,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 5,
      weight: 2,
      curves: 3,
      straights: 1,
      rain: 4,           // weather heavily affects dirt/gravel
      fog: 0,
      rocky: 5,
    },

    Foggy: {
      grip: 4,
      handling: 3,
      deceleration: 3,
      torquehigh: 1,
      torquelow: 3,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 3,
      straights: 1,
      rain: 0,
      fog: 3,            // visibility reduces speed/cornering judgment
      rocky: 5,
    },
    Snowy: {
      grip: 6,
      handling: 4,
      deceleration: 4,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 5,
      weight: 2,
      curves: 3,
      straights: 1,
      rain: 6,
      fog: 2,
      rocky: 5,
    }
  },
  'Proving Grounds': {
    Sunny: {
      grip: 3,
      handling: 3,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 3,
      reliability: 1,
      weight: 1,
      curves: 3,
      straights: 3,
      rain: 0,
      fog: 0,
      rocky: 0,
    },

    Rainy: {
      grip: 5,
      handling: 4,
      deceleration: 4,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 2,
      reliability: 2,
      weight: 1,
      curves: 3,
      straights: 2,
      rain: 4,
      fog: 0,
      rocky: 0,
    },

    Foggy: {
      grip: 4,
      handling: 4,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 2,
      reliability: 2,
      weight: 1,
      curves: 3,
      straights: 3,
      rain: 0,
      fog: 4,
      rocky: 0,
    },
    Snowy: {
      grip: 6,
      handling: 5,
      deceleration: 5,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 1,
      reliability: 3,
      weight: 2,
      curves: 3,
      straights: 2,
      rain: 6,
      fog: 3,
      rocky: 0,
    },
  },
  Bridge: {
    Sunny: {
      grip: 1,
      handling: 2,
      deceleration: 1,
      torquehigh: 4,
      torquelow: 1,
      topspeed: 5,
      reliability: 2,
      weight: 1,     // lighter is a mild advantage
      curves: 1,
      straights: 5,
      rain: 0,
      fog: 0,
      rocky: 0,
    },
    Rainy: {
      grip: 4,
      handling: 3,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 2,   // still matters, but you can't safely max it
      reliability: 3,
      weight: 2,
      curves: 1,
      straights: 3,
      rain: 4,
      fog: 0,
      rocky: 0,
    },
    Foggy: {
      grip: 2,
      handling: 3,
      deceleration: 3,
      torquehigh: 3,
      torquelow: 1,
      topspeed: 3,
      reliability: 2,
      weight: 1,
      curves: 1,
      straights: 4,
      rain: 0,
      fog: 3,
      rocky: 0,
    },
    Snowy: {
      grip: 5,
      handling: 4,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 1,
      reliability: 3,
      weight: 2,     // ice makes lighter cars twitchy but heavy cars struggle to stop
      curves: 1,
      straights: 3,
      rain: 6,
      fog: 2,
      rocky: 0,
    },
  },
  Runway: {
    Sunny: {
      grip: 1,
      handling: 1,
      deceleration: 1,
      torquehigh: 4,
      torquelow: 1,
      topspeed: 5,
      reliability: 2,
      weight: 1,
      curves: 0,
      straights: 5,
      rain: 0,
      fog: 0,
      rocky: 0,
    },
    Rainy: {
      grip: 3,
      handling: 2,
      deceleration: 3,
      torquehigh: 3,
      torquelow: 1,
      topspeed: 3,
      reliability: 3,
      weight: 1,
      curves: 0,
      straights: 4,
      rain: 3,
      fog: 0,
      rocky: 0,
    },
    Foggy: {
      grip: 2,
      handling: 2,
      deceleration: 2,
      torquehigh: 3,
      torquelow: 1,
      topspeed: 4,
      reliability: 2,
      weight: 1,
      curves: 0,
      straights: 4,
      rain: 0,
      fog: 3,
      rocky: 0,
    },
    Snowy: {
      grip: 5,
      handling: 3,
      deceleration: 4,
      torquehigh: 2,
      torquelow: 1,
      topspeed: 1,
      reliability: 3,
      weight: 2,
      curves: 0,
      straights: 2,
      rain: 6,
      fog: 2,
      rocky: 0,
    },
  },
  'Mountain Pass': {
    Sunny: {
      grip: 3,
      handling: 5,
      deceleration: 3,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 1,
      reliability: 2,
      weight: 2,
      curves: 5,
      straights: 1,
      rain: 0,
      fog: 0,
      rocky: 2,
    },
    Rainy: {
      grip: 5,
      handling: 5,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 0,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 4,
      fog: 0,
      rocky: 3,
    },
    Foggy: {
      grip: 4,
      handling: 5,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 0,
      reliability: 3,
      weight: 2,
      curves: 5,
      straights: 1,
      rain: 0,
      fog: 4,
      rocky: 2,
    },
    Snowy: {
      grip: 6,
      handling: 6,
      deceleration: 5,
      torquehigh: 0,
      torquelow: 2,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 5,
      straights: 0,
      rain: 6,
      fog: 3,
      rocky: 3,
    },
  },
  Canyon: {
    Sunny: {
      grip: 3,
      handling: 3,
      deceleration: 3,
      torquehigh: 1,
      torquelow: 3,
      topspeed: 1,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 2,
      rain: 0,
      fog: 0,
      rocky: 4,
    },
    Rainy: {
      grip: 5,
      handling: 4,
      deceleration: 4,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 4,
      fog: 0,
      rocky: 5,
    },
    Foggy: {
      grip: 4,
      handling: 4,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 3,
      topspeed: 0,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 0,
      fog: 4,
      rocky: 4,
    },
    Snowy: {
      grip: 6,
      handling: 5,
      deceleration: 5,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 6,
      fog: 3,
      rocky: 5,
    },
  },
  'City Grid': {
    Sunny: {
      grip: 3,
      handling: 4,
      deceleration: 4,
      torquehigh: 1,
      torquelow: 2,
      topspeed: 1,
      reliability: 2,
      weight: 1,
      curves: 5,
      straights: 1,
      rain: 0,
      fog: 0,
      rocky: 1,
    },
    Rainy: {
      grip: 5,
      handling: 4,
      deceleration: 5,
      torquehigh: 0,
      torquelow: 2,
      topspeed: 0,
      reliability: 3,
      weight: 1,
      curves: 4,
      straights: 1,
      rain: 4,
      fog: 0,
      rocky: 1,
    },
    Foggy: {
      grip: 4,
      handling: 4,
      deceleration: 4,
      torquehigh: 0,
      torquelow: 2,
      topspeed: 1,
      reliability: 2,
      weight: 1,
      curves: 4,
      straights: 1,
      rain: 0,
      fog: 4,
      rocky: 1,
    },
    Snowy: {
      grip: 6,
      handling: 5,
      deceleration: 6,
      torquehigh: 0,
      torquelow: 2,
      topspeed: 0,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 6,
      fog: 3,
      rocky: 1,
    },
  },
  'Desert Flats': {
    Sunny: {
      grip: 1,
      handling: 1,
      deceleration: 1,
      torquehigh: 3,
      torquelow: 2,
      topspeed: 5,
      reliability: 1,
      weight: 1,
      curves: 1,
      straights: 5,
      rain: 0,
      fog: 0,
      rocky: 1,
    },
    Rainy: {
      grip: 3,
      handling: 2,
      deceleration: 2,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 3,
      reliability: 2,
      weight: 1,
      curves: 1,
      straights: 4,
      rain: 4,
      fog: 0,
      rocky: 2,
    },
    Foggy: {
      grip: 2,
      handling: 2,
      deceleration: 2,
      torquehigh: 2,
      torquelow: 2,
      topspeed: 4,
      reliability: 2,
      weight: 1,
      curves: 1,
      straights: 4,
      rain: 0,
      fog: 4,
      rocky: 1,
    },
  },
  'Forest Trail': {
    Sunny: {
      grip: 3,
      handling: 4,
      deceleration: 3,
      torquehigh: 1,
      torquelow: 3,
      topspeed: 1,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 0,
      fog: 0,
      rocky: 4,
    },
    Rainy: {
      grip: 5,
      handling: 4,
      deceleration: 4,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 3,
      straights: 1,
      rain: 4,
      fog: 0,
      rocky: 5,
    },
    Foggy: {
      grip: 4,
      handling: 4,
      deceleration: 4,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 3,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 0,
      fog: 4,
      rocky: 4,
    },
    Snowy: {
      grip: 6,
      handling: 5,
      deceleration: 5,
      torquehigh: 0,
      torquelow: 3,
      topspeed: 0,
      reliability: 4,
      weight: 2,
      curves: 4,
      straights: 1,
      rain: 6,
      fog: 3,
      rocky: 5,
    },
  },
};
